/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.JInternalFrame;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import modelo.persona.Usuario;
import vista.LoginForm;

/**
 *
 * @author zulmi
 */
public class MenuPrincipal extends JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    private Usuario usuario;
    
    private void mostrarModulo(JInternalFrame frame) {
        //Primero valida que no haya una ventana abierta
        if(Ventana.getAllFrames().length > 0){
            JOptionPane.showMessageDialog(this,"Primero cierre la ventana actual.");
            return;
        }
        // Colocar la ventana al centro
        int x = (Ventana.getWidth() - frame.getWidth()) / 2, y = (Ventana.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        // Mostrar en la ventana del menu
        Ventana.add(frame);
        frame.setVisible(true);
    }
    //
    //Constructor, No Tocar!!
    public MenuPrincipal(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuario = usuario;
        configurarPermisos();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    //
    //
    private void configurarPermisos() {
        switch(usuario.getRol()){
            case ADMINISTRADOR:
                break;
            case BIBLIOTECARIO:
                menuUsuarios.setVisible(false);
                menuReportes.setVisible(false);
                break;
            case LECTOR:
                menuUsuarios.setVisible(false);
                menuLibros.setVisible(false);
                menuReportes.setVisible(false);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Ventana = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        ItemSalir = new javax.swing.JMenuItem();
        ItemCerrarSesion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuLibros = new javax.swing.JMenu();
        ItemGestionLibros = new javax.swing.JMenuItem();
        ItemGestionarCategoria = new javax.swing.JMenuItem();
        ItemGestionarAutor = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        ItemGestionUsuarios = new javax.swing.JMenuItem();
        menuPrestamos = new javax.swing.JMenu();
        ItemGestionPrestamo = new javax.swing.JMenuItem();
        itemGestionColas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ventana.setBackground(new java.awt.Color(255, 255, 249));

        jLabel1.setBackground(new java.awt.Color(0, 0, 150));
        jLabel1.setFont(new java.awt.Font("Ravie", 2, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGEBIM");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Gestion Bibliotecaria Municipal :)");

        Ventana.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Ventana.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout VentanaLayout = new javax.swing.GroupLayout(Ventana);
        Ventana.setLayout(VentanaLayout);
        VentanaLayout.setHorizontalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaLayout.createSequentialGroup()
                .addGroup(VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaLayout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaLayout.setVerticalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        jButton1.setText("Acceso Rapido a GestionLibro");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setText("Acceso Rapido a GestionUsuarios");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText("Acceso Rapido a GestionPrestamos");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setText("Acceso Rapido a GestionDevoluciones");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setText("Acceso Rapido a Calcular Multa");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuArchivo.setText("Archivo");

        ItemSalir.setText("Salir");
        ItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(ItemSalir);

        ItemCerrarSesion.setText("Cerrar Sesion");
        ItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCerrarSesionActionPerformed(evt);
            }
        });
        menuArchivo.add(ItemCerrarSesion);

        jMenuBar1.add(menuArchivo);

        jMenu4.setText("Gestion");

        menuLibros.setText("Libros");

        ItemGestionLibros.setText("Gestion de Libros");
        ItemGestionLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionLibrosActionPerformed(evt);
            }
        });
        menuLibros.add(ItemGestionLibros);

        ItemGestionarCategoria.setText("Gestionar las Categorias");
        ItemGestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionarCategoriaActionPerformed(evt);
            }
        });
        menuLibros.add(ItemGestionarCategoria);

        ItemGestionarAutor.setText("Gestionar los Autores");
        ItemGestionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionarAutorActionPerformed(evt);
            }
        });
        menuLibros.add(ItemGestionarAutor);

        jMenu4.add(menuLibros);

        menuUsuarios.setText("Usuarios");

        ItemGestionUsuarios.setText("Gestion de Usuarios");
        ItemGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(ItemGestionUsuarios);

        jMenu4.add(menuUsuarios);

        menuPrestamos.setText("Prestamos");

        ItemGestionPrestamo.setText("Gestion de Prestamos");
        ItemGestionPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionPrestamoActionPerformed(evt);
            }
        });
        menuPrestamos.add(ItemGestionPrestamo);

        itemGestionColas.setText("Gestionar Colas");
        itemGestionColas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionColasActionPerformed(evt);
            }
        });
        menuPrestamos.add(itemGestionColas);

        jMenu4.add(menuPrestamos);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Operaciones");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Consultas");
        jMenuBar1.add(jMenu5);

        jMenu1.setText("Herramientas");
        jMenuBar1.add(jMenu1);

        menuReportes.setText("Reportes");

        jMenu11.setText("Reporte de Libros");

        jMenuItem7.setText("Ver Cantidad de Libros");
        jMenu11.add(jMenuItem7);

        menuReportes.add(jMenu11);

        jMenu12.setText("Reporte de Usuarios");

        jMenuItem8.setText("Ver Usuarios");
        jMenu12.add(jMenuItem8);

        menuReportes.add(jMenu12);

        jMenu13.setText("Reporte de Prestamos");

        jMenuItem9.setText("Ver Prestamos");
        jMenu13.add(jMenuItem9);

        menuReportes.add(jMenu13);

        jMenuBar1.add(menuReportes);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ventana))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemGestionLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionLibrosActionPerformed
        mostrarModulo(new GestionLibro());
    }//GEN-LAST:event_ItemGestionLibrosActionPerformed

    private void ItemGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionUsuariosActionPerformed
        mostrarModulo(new GestionarUsuario());
    }//GEN-LAST:event_ItemGestionUsuariosActionPerformed

    private void ItemGestionPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionPrestamoActionPerformed
        mostrarModulo(new GestionPrestamo());
    }//GEN-LAST:event_ItemGestionPrestamoActionPerformed

    private void ItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSalirActionPerformed
        int salir=JOptionPane.showConfirmDialog(this, "Desea Salir de todo el sistema?","Confirmar Salida", JOptionPane.YES_NO_OPTION);
        if(salir==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_ItemSalirActionPerformed

    private void ItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCerrarSesionActionPerformed
        LoginForm login= new LoginForm();
        login.setVisible(true);
        JOptionPane.showMessageDialog(this, "Cerrando Sesion..., " + "Deme un 20 profe ;)");
        this.dispose();
    }//GEN-LAST:event_ItemCerrarSesionActionPerformed

    private void ItemGestionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionarAutorActionPerformed
        mostrarModulo(new GestionarAutor());
    }//GEN-LAST:event_ItemGestionarAutorActionPerformed

    private void ItemGestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionarCategoriaActionPerformed
        mostrarModulo(new GestionarCategoria());
    }//GEN-LAST:event_ItemGestionarCategoriaActionPerformed

    private void itemGestionColasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionColasActionPerformed
        mostrarModulo(new GestionColas());
    }//GEN-LAST:event_itemGestionColasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCerrarSesion;
    private javax.swing.JMenuItem ItemGestionLibros;
    private javax.swing.JMenuItem ItemGestionPrestamo;
    private javax.swing.JMenuItem ItemGestionUsuarios;
    private javax.swing.JMenuItem ItemGestionarAutor;
    private javax.swing.JMenuItem ItemGestionarCategoria;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JDesktopPane Ventana;
    private javax.swing.JMenuItem itemGestionColas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuLibros;
    private javax.swing.JMenu menuPrestamos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
