/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.JInternalFrame.herramientas;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.respaldo.ResultadoRespaldo;
import servicios.configuracion.ConfiguracionService;
import servicios.respaldos.RespaldoService;

/**
 *
 * @author zulmi
 */
public class CopiaSeguridadForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form CopiaSeguridadForm
     */
    private final RespaldoService respaldoService = new RespaldoService();
    private final ConfiguracionService configuracionService = new ConfiguracionService();
    
    private final String origen = configuracionService.obtenerConfiguracion().getCarpetaRespaldo();
    
    public void mostrarArchivosDatos(Path carpetaDatos) {
        StringBuilder contenido = new StringBuilder();
        contenido.append("ARCHIVOS QUE SERÁN RESPALDADOS\n");
        contenido.append("--------------------------------------------\n\n");
        try {
            Path[] archivos = respaldoService.listarArchivos(carpetaDatos);
            if (archivos.length == 0) {
                contenido.append("No se encontraron archivos para respaldar.\n");
            } else {
                int cantidad = 0;
                for (Path archivo : archivos) {
                    long tamanio = Files.size(archivo);
                    contenido.append("✓ ").append(archivo.getFileName()).append("\n");
                    contenido.append("  Tamaño: ").append(respaldoService.formatearTamanio(tamanio)).append("\n");
                    contenido.append("  Estado: Disponible\n\n");
                    cantidad++;
                }
                contenido.append("--------------------------------------------\n");
                contenido.append("Total de archivos encontrados: ").append(cantidad);
            }
        } catch (IOException ex) {
            contenido.append("Error al leer los archivos:\n");
            contenido.append(ex.getMessage());
        }
        txtArchivos.setText(contenido.toString());
        txtArchivos.setCaretPosition(0);
    }
    
    public CopiaSeguridadForm() {
        initComponents();
        txtCarpetaDatos.setEditable(false);
        txtCarpetaDatos.setText(origen);
    }
    private void limpiar(){
        txtCarpetaDestino.setText(null);
        txtArchivos.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCarpetaDestino = new javax.swing.JTextField();
        txtCarpetaDatos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArchivos = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        btnRespaldar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 26, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(150, 111, 51));
        jLabel15.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 215, 158));
        jLabel15.setText("SIGEBIM - CREAR COPIA DE SEGURIDAD");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 540, -1));

        txtCarpetaDestino.setBackground(new java.awt.Color(242, 224, 189));
        txtCarpetaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCarpetaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarpetaDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCarpetaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 240, -1));

        txtCarpetaDatos.setBackground(new java.awt.Color(242, 224, 189));
        txtCarpetaDatos.setForeground(new java.awt.Color(255, 255, 255));
        txtCarpetaDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtCarpetaDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 430, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 215, 158));
        jLabel12.setText("Carpeta de Datos:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 215, 158));
        jLabel13.setText("Carpeta de Destino:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtArchivos.setBackground(new java.awt.Color(242, 224, 189));
        txtArchivos.setColumns(20);
        txtArchivos.setRows(5);
        txtArchivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtArchivos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 428, 204));

        jLabel16.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 215, 158));
        jLabel16.setText("Archivos a Respaldar:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        btnSeleccionar.setBackground(new java.awt.Color(212, 163, 89));
        btnSeleccionar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 215, 158));
        btnSeleccionar.setText("Seleccionar Carpeta...");
        btnSeleccionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 130, 20));

        btnRespaldar.setBackground(new java.awt.Color(27, 73, 125));
        btnRespaldar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnRespaldar.setForeground(new java.awt.Color(255, 215, 158));
        btnRespaldar.setText("Crear Respaldo");
        btnRespaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespaldarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRespaldar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 129, -1));

        btnLimpiar.setBackground(new java.awt.Color(242, 224, 189));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escoba.png"))); // NOI18N
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 660, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 740, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int resultado = selector.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            txtCarpetaDestino.setText(selector.getSelectedFile().getAbsolutePath());
            mostrarArchivosDatos(Path.of(txtCarpetaDatos.getText()));
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRespaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespaldarActionPerformed
        String origenTexto = txtCarpetaDatos.getText().trim();
        String destinoTexto = txtCarpetaDestino.getText().trim();
        String nombreRespaldo = respaldoService.generarNombreRespaldo();
        
        if (origenTexto.isEmpty() || destinoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Seleccione la carpeta de destino.",
                    "Campo requeridos",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Path carpetaDatos = Path.of(origenTexto);
        Path carpetaDestino = Path.of(destinoTexto);
        Path carpetaNuevoRespaldo = carpetaDestino.resolve(nombreRespaldo);
        
        if (respaldoService.carpetaContieneInformacion(carpetaNuevoRespaldo)) {
            int decision = JOptionPane.showConfirmDialog(this, 
                    "Ya existe una carpeta de respaldo con el nombre:\n\n" 
                            + nombreRespaldo + "\n\nEsta carpeta contiene información."
                            + "\nSi continúa, su contenido será reemplazado."
                            + "\n\n¿Desea realizar el respaldo de todos modos?",
                    "Respaldo existente",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if (decision != JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this,"La copia de seguridad fue cancelada.",
                        "Operación cancelada",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        ResultadoRespaldo resultado = respaldoService.crearRespaldo(carpetaDatos,carpetaDestino);
        JOptionPane.showMessageDialog(this,resultado.getMensaje(),
                resultado.isExitoso() ? "Respaldo completado" : "Error",
                resultado.isExitoso() ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE);
        if (resultado.isExitoso()) {
            txtArchivos.append(
                    "\n\n------------------------------------------"
                    + "\nRESPALDO CREADO CORRECTAMENTE"
                    + "\nUbicación: " + resultado.getRuta()
            );
        }
    }//GEN-LAST:event_btnRespaldarActionPerformed

    private void txtCarpetaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarpetaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarpetaDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRespaldar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArchivos;
    private javax.swing.JTextField txtCarpetaDatos;
    private javax.swing.JTextField txtCarpetaDestino;
    // End of variables declaration//GEN-END:variables
}
