/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.JInternalFrame.herramientas;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.persona.Usuario;
import modelo.respaldo.ResultadoRespaldo;
import servicios.respaldos.RegistroActividadService;
import servicios.respaldos.RespaldoService;

/**
 *
 * @author zulmi
 */
public class CopiaSeguridadForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form CopiaSeguridadForm
     */
    private final RespaldoService respaldoService = new RespaldoService();
    private final String origen = "C:\\SIGEBIM\\SIGEBIM\\data";   
    private final Usuario usuarioActual;
    private final RegistroActividadService registroActividadService;
    
    public void mostrarArchivosDatos(Path carpetaDatos) {
        StringBuilder contenido = new StringBuilder();
        contenido.append("ARCHIVOS QUE SERÁN RESPALDADOS\n");
        contenido.append("--------------------------------------------\n\n");
        try {
            Path[] archivos = respaldoService.listarArchivos(carpetaDatos);
            if (archivos.length == 0) {
                contenido.append("No se encontraron archivos para respaldar.\n");
            } else {
                int cantidad = 0;
                for (Path archivo : archivos) {
                    long tamanio = Files.size(archivo);
                    contenido.append("✓ ").append(archivo.getFileName()).append("\n");
                    contenido.append("  Tamaño: ").append(respaldoService.formatearTamanio(tamanio)).append("\n");
                    contenido.append("  Estado: Disponible\n\n");
                    cantidad++;
                }
                contenido.append("--------------------------------------------\n");
                contenido.append("Total de archivos encontrados: ").append(cantidad);
            }
        } catch (IOException ex) {
            contenido.append("Error al leer los archivos:\n");
            contenido.append(ex.getMessage());
        }
        txtArchivos.setText(contenido.toString());
        txtArchivos.setCaretPosition(0);
    }
    
    public CopiaSeguridadForm(Usuario usuarioActual, RegistroActividadService registroActividadService) {
        initComponents();
        txtCarpetaDatos.setEditable(false);
        txtCarpetaDatos.setText(origen);
        this.usuarioActual = usuarioActual;
        this.registroActividadService = registroActividadService;
    }
    private void limpiar(){
        txtCarpetaDestino.setText(null);
        txtArchivos.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCarpetaDestino = new javax.swing.JTextField();
        txtCarpetaDatos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArchivos = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        btnRespaldar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        jLabel15.setBackground(new java.awt.Color(150, 111, 51));
        jLabel15.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 95, 115));
        jLabel15.setText("SIGEBIM - CREAR COPIA DE SEGURIDAD");

        txtCarpetaDatos.setBackground(new java.awt.Color(60, 60, 60));
        txtCarpetaDatos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setText("Carpeta de Datos:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setText("Carpeta de Destino:");

        txtArchivos.setColumns(20);
        txtArchivos.setRows(5);
        jScrollPane1.setViewportView(txtArchivos);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setText("Archivos a Respaldar:");

        btnSeleccionar.setText("Seleccionar Carpeta...");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnRespaldar.setText("Crear Respaldo");
        btnRespaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespaldarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 249));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escoba.png"))); // NOI18N
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(btnLimpiar)
                            .addComponent(btnRespaldar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCarpetaDestino)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeleccionar))
                            .addComponent(jScrollPane1)
                            .addComponent(txtCarpetaDatos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnClose))
                    .addComponent(jLabel15))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCarpetaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(btnRespaldar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int resultado = selector.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            txtCarpetaDestino.setText(selector.getSelectedFile().getAbsolutePath());
            mostrarArchivosDatos(Path.of(txtCarpetaDatos.getText()));
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRespaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespaldarActionPerformed
        String origenTexto = txtCarpetaDatos.getText().trim();
        String destinoTexto = txtCarpetaDestino.getText().trim();
        String nombreRespaldo = respaldoService.generarNombreRespaldo();
        
        if (origenTexto.isEmpty() || destinoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Seleccione la carpeta de destino.",
                    "Campo requeridos",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Path carpetaDatos = Path.of(origenTexto);
        Path carpetaDestino = Path.of(destinoTexto);
        Path carpetaNuevoRespaldo = carpetaDestino.resolve(nombreRespaldo);
        
        if (respaldoService.carpetaContieneInformacion(carpetaNuevoRespaldo)) {
            int decision = JOptionPane.showConfirmDialog(this, 
                    "Ya existe una carpeta de respaldo con el nombre:\n\n" 
                            + nombreRespaldo + "\n\nEsta carpeta contiene información."
                            + "\nSi continúa, su contenido será reemplazado."
                            + "\n\n¿Desea realizar el respaldo de todos modos?",
                    "Respaldo existente",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if (decision != JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this,"La copia de seguridad fue cancelada.",
                        "Operación cancelada",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        ResultadoRespaldo resultado = respaldoService.crearRespaldo(carpetaDatos,carpetaDestino);
        registroActividadService.registrar(usuarioActual,"Respaldo","Copia de Seguridad",
                "Realizo copia de seguridad en su carpeta: "+carpetaDestino+"\nCon el nombre de"+nombreRespaldo,true);
        JOptionPane.showMessageDialog(this,resultado.getMensaje(),
                resultado.isExitoso() ? "Respaldo completado" : "Error",
                resultado.isExitoso() ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE);
        if (resultado.isExitoso()) {
            txtArchivos.append(
                    "\n\n------------------------------------------"
                    + "\nRESPALDO CREADO CORRECTAMENTE"
                    + "\nUbicación: " + resultado.getRuta()
            );
        }
    }//GEN-LAST:event_btnRespaldarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRespaldar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArchivos;
    private javax.swing.JTextField txtCarpetaDatos;
    private javax.swing.JTextField txtCarpetaDestino;
    // End of variables declaration//GEN-END:variables
}
