/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.JInternalFrame.herramientas;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.respaldo.ResultadoRespaldo;
import servicios.respaldos.RespaldoService;

/**
 *
 * @author zulmi
 */
public class ImportarInfoForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form RestaurarInfoForm
     */
    private final RespaldoService respaldoService = new RespaldoService();
    
    private void mostrarContenidoRespaldo(Path carpetaRespaldo) {
        StringBuilder contenido = new StringBuilder();
        contenido.append("CONTENIDO DEL RESPALDO\n");
        contenido.append("--------------------------------------------\n\n");
        try {
            Path[] archivos = respaldoService.listarArchivos(carpetaRespaldo);
            if (archivos.length == 0) {
                contenido.append("No se encontraron archivos en el respaldo.\n");
                txtCantidad.setText("0");
                txtArchivosRespaldo.setText(contenido.toString());
                return;
            }
            for (Path archivo : archivos) {
                long tamanio = Files.size(archivo);
                contenido.append("✓ ").append(archivo.getFileName()).append("\n");
                contenido.append("  Tamaño: ").append(respaldoService.formatearTamanio(tamanio)).append("\n");
                contenido.append("  Estado: Correcto\n\n");
            }
            contenido.append("--------------------------------------------\n");
            contenido.append("Cantidad de archivos: ").append(archivos.length).append("\n\n");
            if (respaldoService.validarRespaldo(carpetaRespaldo)) {
                contenido.append("El respaldo puede ser restaurado.");
            } else {
                contenido.append("Advertencia: el respaldo está incompleto.");
            }
            txtCantidad.setText(String.valueOf(archivos.length));
            LocalDateTime fecha = respaldoService.obtenerFechaModificacion(carpetaRespaldo);
            if (fecha != null) {
                txtFechaRespaldo.setText(fecha.format(
                                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
            }
        } catch (IOException ex) {
            contenido.append("Error al verificar el respaldo:\n");
            contenido.append(ex.getMessage());
        }
        txtArchivosRespaldo.setText(contenido.toString());
        txtArchivosRespaldo.setCaretPosition(0);
    }
        
    public ImportarInfoForm() {
        initComponents();
        txtCarpetaRespaldo.setEditable(false);
        txtFechaRespaldo.setEditable(false);
        txtCantidad.setEditable(false);
    }
    
    private void limpiar(){
        txtCarpetaRespaldo.setText(null);
        txtFechaRespaldo.setText(null);
        txtCantidad.setText(null);
        txtArchivosRespaldo.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCarpetaDatos = new javax.swing.JTextField();
        txtCarpetaRespaldo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFechaRespaldo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArchivosRespaldo = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 26, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(150, 111, 51));
        jLabel15.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 215, 158));
        jLabel15.setText("SIGEBIM - CREAR COPIA DE SEGURIDAD");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 540, -1));

        txtCarpetaDatos.setBackground(new java.awt.Color(242, 224, 189));
        txtCarpetaDatos.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtCarpetaDatos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCarpetaDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 426, -1));

        txtCarpetaRespaldo.setBackground(new java.awt.Color(242, 224, 189));
        txtCarpetaRespaldo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(txtCarpetaRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 263, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 215, 158));
        jLabel12.setText("Carpeta de Respaldo:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 215, 158));
        jLabel13.setText("Carpeta de Datos:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtFechaRespaldo.setBackground(new java.awt.Color(242, 224, 189));
        txtFechaRespaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFechaRespaldo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtFechaRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 215, 158));
        jLabel14.setText("Fecha de respaldo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 136, -1));

        txtArchivosRespaldo.setBackground(new java.awt.Color(242, 224, 189));
        txtArchivosRespaldo.setColumns(20);
        txtArchivosRespaldo.setRows(5);
        jScrollPane1.setViewportView(txtArchivosRespaldo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 426, 215));

        jLabel16.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 215, 158));
        jLabel16.setText("Cantidad de archivos:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        btnVerificar.setBackground(new java.awt.Color(17, 92, 58));
        btnVerificar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(255, 215, 158));
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 136, -1));

        btnLimpiar.setBackground(new java.awt.Color(242, 224, 189));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escoba.png"))); // NOI18N
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 70, 50));

        btnSeleccionar.setBackground(new java.awt.Color(212, 163, 89));
        btnSeleccionar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 215, 158));
        btnSeleccionar.setText("Seleccionar Carpeta...");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        btnRestaurar.setBackground(new java.awt.Color(27, 73, 125));
        btnRestaurar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnRestaurar.setForeground(new java.awt.Color(255, 215, 158));
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 136, -1));

        txtCantidad.setBackground(new java.awt.Color(242, 224, 189));
        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 119, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 710, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int resultado = selector.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            txtCarpetaRespaldo.setText(selector.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
         String ruta = txtCarpetaRespaldo.getText().trim();
        if (ruta.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Seleccione una carpeta de respaldo.",
                    "Campo requerido",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Path carpetaRespaldo = Path.of(ruta);
        mostrarContenidoRespaldo(carpetaRespaldo);
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        String respaldoTexto = txtCarpetaRespaldo.getText().trim();
        String datosTexto = txtCarpetaDatos.getText().trim();
        if (respaldoTexto.isEmpty() || datosTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Seleccione la carpeta donde respaldo sus archivos");
            return;
        }
        Path carpetaRespaldo = Path.of(respaldoTexto);
        Path carpetaDatos = Path.of(datosTexto);
        if (!respaldoService.validarRespaldo(carpetaRespaldo)) {
            JOptionPane.showMessageDialog(this,"La carpeta seleccionada no contiene un respaldo válido.",
                    "Respaldo inválido",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirmacion = JOptionPane.showConfirmDialog(this,"La restauración reemplazará la información actual.\n"
                        + "¿Desea continuar?","Confirmar restauración",JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        ResultadoRespaldo resultado = respaldoService.restaurarRespaldo(carpetaRespaldo,carpetaDatos);
        JOptionPane.showMessageDialog(this,resultado.getMensaje(),
                resultado.isExitoso() ? "Restauración completada" : "Error",
                resultado.isExitoso() ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE
        );
    }//GEN-LAST:event_btnRestaurarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArchivosRespaldo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCarpetaDatos;
    private javax.swing.JTextField txtCarpetaRespaldo;
    private javax.swing.JTextField txtFechaRespaldo;
    // End of variables declaration//GEN-END:variables
}
