/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.JInternalFrame.herramientas;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.respaldo.ResultadoRespaldo;
import servicios.respaldos.RespaldoService;

/**
 *
 * @author zulmi
 */
public class ImportarInfoForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form RestaurarInfoForm
     */
    private final RespaldoService respaldoService = new RespaldoService();
    
    private void mostrarContenidoRespaldo(Path carpetaRespaldo) {
        StringBuilder contenido = new StringBuilder();
        contenido.append("CONTENIDO DEL RESPALDO\n");
        contenido.append("--------------------------------------------\n\n");
        try {
            Path[] archivos = respaldoService.listarArchivos(carpetaRespaldo);
            if (archivos.length == 0) {
                contenido.append("No se encontraron archivos en el respaldo.\n");
                txtCantidad.setText("0");
                txtArchivosRespaldo.setText(contenido.toString());
                return;
            }
            for (Path archivo : archivos) {
                long tamanio = Files.size(archivo);
                contenido.append("✓ ").append(archivo.getFileName()).append("\n");
                contenido.append("  Tamaño: ").append(respaldoService.formatearTamanio(tamanio)).append("\n");
                contenido.append("  Estado: Correcto\n\n");
            }
            contenido.append("--------------------------------------------\n");
            contenido.append("Cantidad de archivos: ").append(archivos.length).append("\n\n");
            if (respaldoService.validarRespaldo(carpetaRespaldo)) {
                contenido.append("El respaldo puede ser restaurado.");
            } else {
                contenido.append("Advertencia: el respaldo está incompleto.");
            }
            txtCantidad.setText(String.valueOf(archivos.length));
            LocalDateTime fecha = respaldoService.obtenerFechaModificacion(carpetaRespaldo);
            if (fecha != null) {
                txtFechaRespaldo.setText(fecha.format(
                                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
            }
        } catch (IOException ex) {
            contenido.append("Error al verificar el respaldo:\n");
            contenido.append(ex.getMessage());
        }
        txtArchivosRespaldo.setText(contenido.toString());
        txtArchivosRespaldo.setCaretPosition(0);
    }
        
    public ImportarInfoForm() {
        initComponents();
        txtCarpetaRespaldo.setEditable(false);
        txtFechaRespaldo.setEditable(false);
        txtCantidad.setEditable(false);
    }
    
    private void limpiar(){
        txtCarpetaRespaldo.setText(null);
        txtFechaRespaldo.setText(null);
        txtCantidad.setText(null);
        txtArchivosRespaldo.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCarpetaDatos = new javax.swing.JTextField();
        txtCarpetaRespaldo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFechaRespaldo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArchivosRespaldo = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();

        jLabel15.setBackground(new java.awt.Color(150, 111, 51));
        jLabel15.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 95, 115));
        jLabel15.setText("SIGEBIM - CREAR COPIA DE SEGURIDAD");

        txtCarpetaDatos.setBackground(new java.awt.Color(60, 60, 60));
        txtCarpetaDatos.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtCarpetaDatos.setForeground(new java.awt.Color(255, 255, 255));

        txtCarpetaRespaldo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setText("Carpeta de Respaldo:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setText("Carpeta de Datos:");

        txtFechaRespaldo.setBackground(new java.awt.Color(60, 60, 60));
        txtFechaRespaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFechaRespaldo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setText("Fecha de respaldo:");

        txtArchivosRespaldo.setColumns(20);
        txtArchivosRespaldo.setRows(5);
        jScrollPane1.setViewportView(txtArchivosRespaldo);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setText("Cantidad de archivos:");

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 249));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escoba.png"))); // NOI18N
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSeleccionar.setText("Seleccionar Carpeta...");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        txtCantidad.setBackground(new java.awt.Color(60, 60, 60));
        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRestaurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCarpetaRespaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSeleccionar))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFechaRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addComponent(txtCarpetaDatos))
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnClose))
                    .addComponent(jLabel15))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCarpetaRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeleccionar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarpetaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFechaRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVerificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurar)
                        .addGap(51, 51, 51)
                        .addComponent(btnLimpiar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int resultado = selector.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            txtCarpetaRespaldo.setText(selector.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
         String ruta = txtCarpetaRespaldo.getText().trim();
        if (ruta.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Seleccione una carpeta de respaldo.",
                    "Campo requerido",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Path carpetaRespaldo = Path.of(ruta);
        mostrarContenidoRespaldo(carpetaRespaldo);
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        String respaldoTexto = txtCarpetaRespaldo.getText().trim();
        String datosTexto = txtCarpetaDatos.getText().trim();
        if (respaldoTexto.isEmpty() || datosTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Seleccione la carpeta donde respaldo sus archivos");
            return;
        }
        Path carpetaRespaldo = Path.of(respaldoTexto);
        Path carpetaDatos = Path.of(datosTexto);
        if (!respaldoService.validarRespaldo(carpetaRespaldo)) {
            JOptionPane.showMessageDialog(this,"La carpeta seleccionada no contiene un respaldo válido.",
                    "Respaldo inválido",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirmacion = JOptionPane.showConfirmDialog(this,"La restauración reemplazará la información actual.\n"
                        + "¿Desea continuar?","Confirmar restauración",JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        ResultadoRespaldo resultado = respaldoService.restaurarRespaldo(carpetaRespaldo,carpetaDatos);
        JOptionPane.showMessageDialog(this,resultado.getMensaje(),
                resultado.isExitoso() ? "Restauración completada" : "Error",
                resultado.isExitoso() ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE
        );
    }//GEN-LAST:event_btnRestaurarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArchivosRespaldo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCarpetaDatos;
    private javax.swing.JTextField txtCarpetaRespaldo;
    private javax.swing.JTextField txtFechaRespaldo;
    // End of variables declaration//GEN-END:variables
}
