/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.JInternalFrame;

import archivos.ArchivoLibro;
import archivos.ArchivoPrestamo;
import archivos.ArchivoUsuario;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.libro.Libro;
import modelo.persona.Usuario;
import modelo.prestamo.ColaDeEspera;
import modelo.prestamo.Devolucion;
import modelo.prestamo.Multa;
import modelo.prestamo.Prestamo;
import servicios.libros.PrestamoService;
import util.PanelFondo;
import util.TablaUtil;

/**
 *
 * @author jerem
 */
public class GestionDevolucion extends javax.swing.JInternalFrame {

    // Tarifa de multa por dia de retraso. Ajustar aqui si cambia la politica de la biblioteca.
    private static final double TARIFA_MULTA_DIA = 1.0;
 
    private ArrayList<Libro> listaLibros;
    private ArrayList<Usuario> listaUsuarios;
    private ArrayList<Prestamo> listaPrestamos;
 
    private final ArchivoLibro archivoLibro = new ArchivoLibro();
    private final ArchivoUsuario archivoUsuario = new ArchivoUsuario();
    private final ArchivoPrestamo archivoPrestamo = new ArchivoPrestamo();
 
    private PrestamoService prestamoService;
 
    // Prestamo localizado en la ultima busqueda, pendiente de confirmar su devolucion
    private Prestamo prestamoEncontrado;
    
    /**
     * Creates new form GestionDevolucion
     */
    public GestionDevolucion() {
        initComponents();
        listaLibros = archivoLibro.cargarLibros();
        listaUsuarios = archivoUsuario.cargarUsuarios();
        listaPrestamos = archivoPrestamo.cargarPrestamos(listaLibros, listaUsuarios);
        prestamoService = new PrestamoService(listaPrestamos);
 
        llenarTablaDevolucion();
        btnDevolucion1.setEnabled(false);
        
        util.TablaUtil.aplicarEstiloYFormato(jScrollPane1, tblDevolucion);
    }

    private void llenarTablaDevolucion() {
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloTabla.addColumn("ID Prestamo");
        modeloTabla.addColumn("ISBN");
        modeloTabla.addColumn("Libro");
        modeloTabla.addColumn("Usuario");
        modeloTabla.addColumn("Fecha Prestamo");
        modeloTabla.addColumn("Fecha Limite");
        modeloTabla.addColumn("Dias Retraso");
        modeloTabla.addColumn("Multa (S/.)");
        modeloTabla.addColumn("Estado");
        tblDevolucion.setModel(modeloTabla);
    }
 
    private long calcularDiasRetraso(Prestamo prestamo) {
        return Math.max(0, ChronoUnit.DAYS.between(prestamo.getFechaLimite(), LocalDate.now()));
    }
 
    private void mostrarPrestamoEnTabla(Prestamo prestamo) {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblDevolucion.getModel();
        modeloTabla.setRowCount(0);
 
        long diasRetraso = calcularDiasRetraso(prestamo);
        double montoMulta = diasRetraso * TARIFA_MULTA_DIA;
 
        Object[] fila = {
            prestamo.getIdPrestamo(),
            prestamo.getLibro().getIsbn(),
            prestamo.getLibro().getTitulo(),
            prestamo.getUsuario().getNombre(),
            prestamo.getFechaPrestamo(),
            prestamo.getFechaLimite(),
            diasRetraso,
            String.format("%.2f", montoMulta),
            prestamo.getEstadoPrestamo().getTexto()
        };
        modeloTabla.addRow(fila);
        util.TablaUtil.aplicarEstiloYFormato(jScrollPane1, tblDevolucion);
    }
 
    private void limpiar() {
        txtIdPrestamo.setText("");
        prestamoEncontrado = null;
        btnDevolucion1.setEnabled(false);
        DefaultTableModel modeloTabla = (DefaultTableModel) tblDevolucion.getModel();
        modeloTabla.setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelFondo("/img/FondoInt.jpg");
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new util.PanelGuinda();
        jLabel2 = new javax.swing.JLabel();
        txtIdPrestamo = new javax.swing.JTextField();
        btnDevolucion1 = new javax.swing.JButton();
        btnBuscarr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevolucion = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 235, 215));
        jLabel1.setText("GESTIÓN DEVOLUCIÓN");

        jPanel2.setBackground(new java.awt.Color(80, 50, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 235, 215));
        jLabel2.setText("Id Prestamo:");

        txtIdPrestamo.setBackground(new java.awt.Color(235, 219, 178));
        txtIdPrestamo.setForeground(new java.awt.Color(60, 35, 20));
        txtIdPrestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        btnDevolucion1.setBackground(new java.awt.Color(139, 69, 19));
        btnDevolucion1.setForeground(new java.awt.Color(245, 235, 215));
        btnDevolucion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/devolucion.png"))); // NOI18N
        btnDevolucion1.setText("Generar Devolucion");
        btnDevolucion1.addActionListener(this::btnDevolucion1ActionPerformed);

        btnBuscarr.setBackground(new java.awt.Color(161, 217, 128));
        btnBuscarr.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnBuscarr.setText("Buscar");
        btnBuscarr.addActionListener(this::btnBuscarrActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnBuscarr, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnDevolucion1)
                .addGap(146, 146, 146))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolucion1)
                    .addComponent(btnBuscarr))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tblDevolucion.setBackground(new java.awt.Color(101, 67, 33));
        tblDevolucion.setForeground(new java.awt.Color(0, 0, 0));
        tblDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDevolucion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolucion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucion1ActionPerformed
        if (prestamoEncontrado == null || !prestamoEncontrado.estaActivo()) {
            JOptionPane.showMessageDialog(this, "Primero busque un prestamo activo valido.");
            return;
        }
 
        Libro libro = prestamoEncontrado.getLibro();
        long diasRetraso = calcularDiasRetraso(prestamoEncontrado);
        double montoMulta = diasRetraso * TARIFA_MULTA_DIA;
 
        boolean devuelto = prestamoService.devolverPrestamo(prestamoEncontrado.getIdPrestamo(), libro);
        if (!devuelto) {
            JOptionPane.showMessageDialog(this, "No se pudo procesar la devolucion.");
            return;
        }
 
        // Registro de la devolucion y, si corresponde, de la multa.
        // Nota: aun no existe un ArchivoDevolucion/ArchivoMulta en el proyecto para
        // persistirlos en disco; por ahora quedan solo en memoria para esta operacion.
        Devolucion devolucion = new Devolucion();
        devolucion.setCodigo("DEV-" + prestamoEncontrado.getIdPrestamo());
        devolucion.setPrestamo(prestamoEncontrado);
        devolucion.setFechaRealDevolucion(LocalDate.now());
 
        String mensaje = "Devolucion registrada correctamente.";
        if (diasRetraso > 0) {
            Multa multa = new Multa("M-" + prestamoEncontrado.getIdPrestamo(), prestamoEncontrado, montoMulta);
            devolucion.setMulta(multa);
            mensaje += String.format("%nDias de retraso: %d%nMulta a cobrar: S/. %.2f", diasRetraso, montoMulta);
        }
 
        archivoLibro.guardarLibros(listaLibros);
        archivoPrestamo.guardarPrestamos(listaPrestamos);
 
        JOptionPane.showMessageDialog(this, mensaje);
 
        if (ColaDeEspera.tieneCola(libro.getIsbn())) {
            Usuario siguiente = ColaDeEspera.atenderSiguiente(libro.getIsbn());
            if (siguiente != null) {
                JOptionPane.showMessageDialog(this,
                        "Siguiente en cola:\nNombre: " + siguiente.getNombre()
                        + "\nCelular: " + siguiente.getCelular(),
                        "Cola de espera", JOptionPane.INFORMATION_MESSAGE);
            }
        }
 
        limpiar();
    }//GEN-LAST:event_btnDevolucion1ActionPerformed

    private void btnBuscarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarrActionPerformed
        String id = txtIdPrestamo.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de prestamo.");
            return;
        }
 
        prestamoEncontrado = prestamoService.buscarPrestamo(id);
        DefaultTableModel modeloTabla = (DefaultTableModel) tblDevolucion.getModel();
        modeloTabla.setRowCount(0);
 
        if (prestamoEncontrado == null) {
            JOptionPane.showMessageDialog(this,
                    "No se encontro un prestamo con ese ID.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            btnDevolucion1.setEnabled(false);
            return;
        }
 
        if (!prestamoEncontrado.estaActivo()) {
            JOptionPane.showMessageDialog(this,
                    "Este prestamo ya fue devuelto o no esta activo.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            prestamoEncontrado = null;
            btnDevolucion1.setEnabled(false);
            return;
        }
 
        mostrarPrestamoEnTabla(prestamoEncontrado);
        btnDevolucion1.setEnabled(true);
    }//GEN-LAST:event_btnBuscarrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarr;
    private javax.swing.JButton btnDevolucion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDevolucion;
    private javax.swing.JTextField txtIdPrestamo;
    // End of variables declaration//GEN-END:variables
}
