/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import modelo.persona.Usuario;
import vista.LoginForm;
//Imports para agregar el fondo de pantalla
import javax.swing.JDesktopPane;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.SwingUtilities;
import servicios.respaldos.RegistroActividadService;
import vista.JInternalFrame.Ayuda.AyudaConfiguracionForm;
import vista.JInternalFrame.Ayuda.AyudaLibroForm;
import vista.JInternalFrame.Ayuda.AyudaPrestamoForm;
import vista.JInternalFrame.Ayuda.AyudaUsuarioForm;
import vista.JInternalFrame.Consultas.ConsultarRegistroActividad;
import vista.JInternalFrame.herramientas.CopiaSeguridadForm;
import vista.JInternalFrame.Gestion.GestionColas;
import vista.JInternalFrame.Gestion.GestionLibro;
import vista.JInternalFrame.Gestion.GestionPrestamo;
import vista.JInternalFrame.Gestion.GestionarAutor;
import vista.JInternalFrame.Gestion.GestionarCategoria;
import vista.JInternalFrame.Gestion.GestionarUsuario;
import vista.JInternalFrame.herramientas.ImportarInfoForm;

/**
 *
 * @author zulmi
 */
public class MenuPrincipal extends JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    private final Usuario usuario;
    private final RegistroActividadService registroActividadService;
    
    private void mostrarModulo(JInternalFrame frame) {
        //Mostrar Ventana en el Menu
        Ventana.add(frame);
        frame.setVisible(true);
        // Colocar la ventana al centro
        int x = (Ventana.getWidth() - frame.getWidth()) / 2, y = (Ventana.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(Math.max(x, 0),Math.max(y, 0));
    }
    private void configurarVentana() {
        Ventana.setLayout(null);
        Ventana.setLayer(lblTitulo, JDesktopPane.DEFAULT_LAYER);
        Ventana.setLayer(lblSubtitulo, JDesktopPane.DEFAULT_LAYER);
        Ventana.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                centrarLabels();
            }
        });

        SwingUtilities.invokeLater(this::centrarLabels);
    }
    
    private void centrarLabels() {
        lblTitulo.setSize(lblTitulo.getPreferredSize());
        lblSubtitulo.setSize(lblSubtitulo.getPreferredSize());
        int centroX = Ventana.getWidth() / 2;
        int centroY = Ventana.getHeight() / 2;
        lblTitulo.setLocation(centroX - lblTitulo.getWidth() / 2, centroY - 90);
        lblSubtitulo.setLocation(centroX - lblSubtitulo.getWidth() / 2,centroY);
    }
    //
    //Constructor, No Tocar!!
    public MenuPrincipal(Usuario usuario, RegistroActividadService registroActividadService) {
        initComponents();
        this.usuario = usuario;
        this.registroActividadService = registroActividadService;
        configurarPermisos();
        configurarVentana();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }
    //
    //
    private void configurarPermisos() {
        switch(usuario.getRol()){
            case ADMINISTRADOR:
                break;
            case BIBLIOTECARIO:
                menuReportes.setVisible(false);
                break;
            case LECTOR:
                menuLibros.setVisible(false);
                menuReportes.setVisible(false);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        Ventana =  new javax.swing.JDesktopPane() {

            private java.awt.Image imagenFondo;

            {
                java.net.URL ruta =
                getClass().getResource("/img/fondo.png");

                if (ruta != null) {
                    imagenFondo = new javax.swing.ImageIcon(ruta).getImage();
                } else {
                    System.err.println("No se encontró la imagen de fondo.");
                }
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);

                if (imagenFondo != null) {
                    g.drawImage(
                        imagenFondo,
                        0,
                        0,
                        getWidth(),
                        getHeight(),
                        this
                    );
                }
            }
        };
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAccesoLibro = new javax.swing.JButton();
        btnAccesoUsuarios = new javax.swing.JButton();
        btnAccesoPrestamos = new javax.swing.JButton();
        btnAccesoDevoluciones = new javax.swing.JButton();
        btnAccesoMulta = new javax.swing.JButton();
        btnAccesoCopiaSeguridad = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        ItemCerrarSesion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuLibros = new javax.swing.JMenu();
        ItemGestionLibros = new javax.swing.JMenuItem();
        ItemGestionarCategoria = new javax.swing.JMenuItem();
        ItemGestionarAutor = new javax.swing.JMenuItem();
        ItemGestionUsuarios = new javax.swing.JMenuItem();
        menuPrestamos = new javax.swing.JMenu();
        ItemGestionPrestamo = new javax.swing.JMenuItem();
        itemGestionColas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemCopiaSeguridad = new javax.swing.JMenuItem();
        intemRestaurar = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        itemRegistroActividad = new javax.swing.JMenuItem();
        itemAyudaUsuarios = new javax.swing.JMenu();
        itemNosotros = new javax.swing.JMenuItem();
        itemAyudaLibros = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        itemAyudaPrestamos = new javax.swing.JMenuItem();
        itemAyudaReportes = new javax.swing.JMenuItem();
        itemAyudaConfiguracion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ventana.setBackground(new java.awt.Color(255, 255, 249));
        Ventana.setName(""); // NOI18N

        lblTitulo.setBackground(new java.awt.Color(0, 0, 150));
        lblTitulo.setFont(new java.awt.Font("Ravie", 2, 72)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("SIGEBIM");

        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Sistema de Gestion Bibliotecaria Municipal :)");

        Ventana.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Ventana.setLayer(lblSubtitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout VentanaLayout = new javax.swing.GroupLayout(Ventana);
        Ventana.setLayout(VentanaLayout);
        VentanaLayout.setHorizontalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaLayout.createSequentialGroup()
                .addGroup(VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaLayout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(lblSubtitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaLayout.setVerticalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        btnAccesoLibro.setText("Acceso Rapido a GestionLibro");
        btnAccesoLibro.setFocusable(false);
        btnAccesoLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccesoLibro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccesoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoLibroActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAccesoLibro);

        btnAccesoUsuarios.setText("Acceso Rapido a GestionUsuarios");
        btnAccesoUsuarios.setFocusable(false);
        btnAccesoUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccesoUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccesoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAccesoUsuarios);

        btnAccesoPrestamos.setText("Acceso Rapido a GestionPrestamos");
        btnAccesoPrestamos.setFocusable(false);
        btnAccesoPrestamos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccesoPrestamos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccesoPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoPrestamosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAccesoPrestamos);

        btnAccesoDevoluciones.setText("Acceso Rapido a GestionDevoluciones");
        btnAccesoDevoluciones.setFocusable(false);
        btnAccesoDevoluciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccesoDevoluciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAccesoDevoluciones);

        btnAccesoMulta.setText("Acceso Rapido a Calcular Multa");
        btnAccesoMulta.setFocusable(false);
        btnAccesoMulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccesoMulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAccesoMulta);

        btnAccesoCopiaSeguridad.setText("Acceso Rapido Crear Copia Seguridad");
        btnAccesoCopiaSeguridad.setFocusable(false);
        btnAccesoCopiaSeguridad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccesoCopiaSeguridad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccesoCopiaSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoCopiaSeguridadActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAccesoCopiaSeguridad);

        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuArchivo.setText("Archivo");

        ItemCerrarSesion.setText("Cerrar Sesion");
        ItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCerrarSesionActionPerformed(evt);
            }
        });
        menuArchivo.add(ItemCerrarSesion);

        jMenuBar1.add(menuArchivo);

        jMenu4.setText("Gestion");

        menuLibros.setText("Mantenimiento de Libros");

        ItemGestionLibros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        ItemGestionLibros.setText("Libros");
        ItemGestionLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionLibrosActionPerformed(evt);
            }
        });
        menuLibros.add(ItemGestionLibros);

        ItemGestionarCategoria.setText("Categorias");
        ItemGestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionarCategoriaActionPerformed(evt);
            }
        });
        menuLibros.add(ItemGestionarCategoria);

        ItemGestionarAutor.setText("Autores");
        ItemGestionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionarAutorActionPerformed(evt);
            }
        });
        menuLibros.add(ItemGestionarAutor);

        jMenu4.add(menuLibros);

        ItemGestionUsuarios.setText("Mantenimiento de usuarios");
        ItemGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(ItemGestionUsuarios);

        menuPrestamos.setText("Mantenimiento de Prestamos");

        ItemGestionPrestamo.setText("Prestamos");
        ItemGestionPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGestionPrestamoActionPerformed(evt);
            }
        });
        menuPrestamos.add(ItemGestionPrestamo);

        itemGestionColas.setText("Colas");
        itemGestionColas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionColasActionPerformed(evt);
            }
        });
        menuPrestamos.add(itemGestionColas);

        jMenu4.add(menuPrestamos);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Consultas");

        menuReportes.setText("Reportes");

        jMenuItem2.setText("Reporte Por Libros");
        menuReportes.add(jMenuItem2);

        jMenuItem3.setText("Reporte Por Usuarios");
        menuReportes.add(jMenuItem3);

        jMenuItem4.setText("Reporte Por Prestamos");
        menuReportes.add(jMenuItem4);

        jMenu5.add(menuReportes);

        jMenuItem5.setText("Catalogo Virtual");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Prestamos Vencidos");
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Herramientas");

        itemCopiaSeguridad.setText("Realizar Copia de Seguridad");
        itemCopiaSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCopiaSeguridadActionPerformed(evt);
            }
        });
        jMenu1.add(itemCopiaSeguridad);

        intemRestaurar.setText("Importar Ficheros");
        intemRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intemRestaurarActionPerformed(evt);
            }
        });
        jMenu1.add(intemRestaurar);

        jMenuItem10.setText("Configuracion del Sistema");
        jMenu1.add(jMenuItem10);

        itemRegistroActividad.setText("Registro de Actividad");
        itemRegistroActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroActividadActionPerformed(evt);
            }
        });
        jMenu1.add(itemRegistroActividad);

        jMenuBar1.add(jMenu1);

        itemAyudaUsuarios.setText("Ayuda");

        itemNosotros.setText("Sobre Nosotros");
        itemNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNosotrosActionPerformed(evt);
            }
        });
        itemAyudaUsuarios.add(itemNosotros);

        itemAyudaLibros.setText("Ayuda a GestionLibros");
        itemAyudaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAyudaLibrosActionPerformed(evt);
            }
        });
        itemAyudaUsuarios.add(itemAyudaLibros);

        jMenuItem7.setText("Ayuda a GestionUsuarios");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        itemAyudaUsuarios.add(jMenuItem7);

        itemAyudaPrestamos.setText("Ayuda a GestionPrestamos");
        itemAyudaPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAyudaPrestamosActionPerformed(evt);
            }
        });
        itemAyudaUsuarios.add(itemAyudaPrestamos);

        itemAyudaReportes.setText("Ayuda a Reportes");
        itemAyudaUsuarios.add(itemAyudaReportes);

        itemAyudaConfiguracion.setText("Ayuda a Configuracion");
        itemAyudaConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAyudaConfiguracionActionPerformed(evt);
            }
        });
        itemAyudaUsuarios.add(itemAyudaConfiguracion);

        jMenuBar1.add(itemAyudaUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
            .addComponent(Ventana)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ventana))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemGestionLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionLibrosActionPerformed
        mostrarModulo(new GestionLibro());
    }//GEN-LAST:event_ItemGestionLibrosActionPerformed

    private void ItemGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionUsuariosActionPerformed
        mostrarModulo(new GestionarUsuario());
    }//GEN-LAST:event_ItemGestionUsuariosActionPerformed

    private void ItemGestionPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionPrestamoActionPerformed
        mostrarModulo(new GestionPrestamo());
    }//GEN-LAST:event_ItemGestionPrestamoActionPerformed

    private void ItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCerrarSesionActionPerformed
        registroActividadService.registrar(usuario,"Seguridad","Cerrar sesión","El usuario cerró su sesión.",
            true);
        JOptionPane.showMessageDialog(this, "Cerrando Sesion..., Deme un 20 profe ;)");
        LoginForm login= new LoginForm(registroActividadService);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemCerrarSesionActionPerformed

    private void ItemGestionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionarAutorActionPerformed
        mostrarModulo(new GestionarAutor());
    }//GEN-LAST:event_ItemGestionarAutorActionPerformed

    private void ItemGestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGestionarCategoriaActionPerformed
        mostrarModulo(new GestionarCategoria());
    }//GEN-LAST:event_ItemGestionarCategoriaActionPerformed

    private void itemGestionColasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionColasActionPerformed
        mostrarModulo(new GestionColas());
    }//GEN-LAST:event_itemGestionColasActionPerformed

    private void itemCopiaSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCopiaSeguridadActionPerformed
        mostrarModulo(new CopiaSeguridadForm(usuario,registroActividadService));
    }//GEN-LAST:event_itemCopiaSeguridadActionPerformed

    private void intemRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intemRestaurarActionPerformed
        mostrarModulo(new ImportarInfoForm());
    }//GEN-LAST:event_intemRestaurarActionPerformed

    private void btnAccesoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoLibroActionPerformed
        mostrarModulo(new GestionLibro());
    }//GEN-LAST:event_btnAccesoLibroActionPerformed

    private void btnAccesoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoUsuariosActionPerformed
        mostrarModulo(new GestionarUsuario());
    }//GEN-LAST:event_btnAccesoUsuariosActionPerformed

    private void btnAccesoPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoPrestamosActionPerformed
        mostrarModulo(new GestionPrestamo());
    }//GEN-LAST:event_btnAccesoPrestamosActionPerformed

    private void btnAccesoCopiaSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoCopiaSeguridadActionPerformed
        mostrarModulo(new CopiaSeguridadForm(usuario,registroActividadService));
    }//GEN-LAST:event_btnAccesoCopiaSeguridadActionPerformed

    private void itemNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNosotrosActionPerformed
        
    }//GEN-LAST:event_itemNosotrosActionPerformed

    private void itemAyudaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAyudaLibrosActionPerformed
        mostrarModulo(new AyudaLibroForm());
    }//GEN-LAST:event_itemAyudaLibrosActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        mostrarModulo(new AyudaUsuarioForm());
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void itemAyudaPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAyudaPrestamosActionPerformed
        mostrarModulo(new AyudaPrestamoForm());
    }//GEN-LAST:event_itemAyudaPrestamosActionPerformed

    private void itemAyudaConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAyudaConfiguracionActionPerformed
        mostrarModulo(new AyudaConfiguracionForm());
    }//GEN-LAST:event_itemAyudaConfiguracionActionPerformed

    private void itemRegistroActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroActividadActionPerformed
        mostrarModulo(new ConsultarRegistroActividad(registroActividadService));
    }//GEN-LAST:event_itemRegistroActividadActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCerrarSesion;
    private javax.swing.JMenuItem ItemGestionLibros;
    private javax.swing.JMenuItem ItemGestionPrestamo;
    private javax.swing.JMenuItem ItemGestionUsuarios;
    private javax.swing.JMenuItem ItemGestionarAutor;
    private javax.swing.JMenuItem ItemGestionarCategoria;
    private javax.swing.JDesktopPane Ventana;
    private javax.swing.JButton btnAccesoCopiaSeguridad;
    private javax.swing.JButton btnAccesoDevoluciones;
    private javax.swing.JButton btnAccesoLibro;
    private javax.swing.JButton btnAccesoMulta;
    private javax.swing.JButton btnAccesoPrestamos;
    private javax.swing.JButton btnAccesoUsuarios;
    private javax.swing.JMenuItem intemRestaurar;
    private javax.swing.JMenuItem itemAyudaConfiguracion;
    private javax.swing.JMenuItem itemAyudaLibros;
    private javax.swing.JMenuItem itemAyudaPrestamos;
    private javax.swing.JMenuItem itemAyudaReportes;
    private javax.swing.JMenu itemAyudaUsuarios;
    private javax.swing.JMenuItem itemCopiaSeguridad;
    private javax.swing.JMenuItem itemGestionColas;
    private javax.swing.JMenuItem itemNosotros;
    private javax.swing.JMenuItem itemRegistroActividad;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuLibros;
    private javax.swing.JMenu menuPrestamos;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
