/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.JInternalFrame.Gestion;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import modelo.libro.Autor;
import servicios.libros.AutorService;
import util.PanelFondo;

/**
 *
 * @author zulmi
 */
public class GestionarAutor extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionAutor2
     */
    private String id, nombre;
    DefaultListModel<String> modelo = new DefaultListModel<>();
    AutorService servicio = new AutorService();
    private void cargarAutores(){
        modelo.clear();
        for (Autor a : servicio.listar()) {
            modelo.addElement(a.getId() + " - " + a.getNombre());
        }
        lstAutores.setModel(modelo);
    }
    private void busqueda(){
        txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            private void filtrar() {
                String texto = txtBuscar.getText().trim().toLowerCase();
                modelo.clear();
                for (Autor a : servicio.listar()) {
                    if (a.getId().toLowerCase().contains(texto) ||
                        a.getNombre().toLowerCase().contains(texto)) {
                        modelo.addElement(a.getId() + " - " + a.getNombre());
                    }
                }
            }
            @Override
            public void insertUpdate(DocumentEvent e) { 
                filtrar(); 
            }
            @Override
            public void removeUpdate(DocumentEvent e) { 
                filtrar(); 
            }
            @Override
            public void changedUpdate(DocumentEvent e) { 
                filtrar(); 
            }
        });
    }
    private void obtenerDatos(){
        id = txtIdAutor.getText().trim();
        nombre = txtNombreAutor.getText().trim();
    }
    private void limpiar(){
        txtIdAutor.setText(null);
        txtNombreAutor.setText(null);
        txtBuscar.setText(null);
        txtIdAutor.requestFocus();
        cargarAutores();
    }
    //
    // Constructor, No Tocar!!
    public GestionarAutor() {
        super("Gestionar Autor - Seccion Bibliotecario", true, true, true, true);
        initComponents();
        cargarAutores();
        busqueda();
    }
    //
    //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelFondo("/img/FondoInt.jpg");
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdAutor = new javax.swing.JTextField();
        txtNombreAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAutores = new javax.swing.JList<>();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 249));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(150, 111, 51));
        jLabel15.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 215, 158));
        jLabel15.setText("SIGEBIM - AUTORES");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 53, 296, -1));

        jPanel2.setBackground(new java.awt.Color(45, 20, 20));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 215, 158));
        jLabel1.setText("Empezar por A-#");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 17, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 215, 158));
        jLabel2.setText("Nombre del Autor:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 41, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 215, 158));
        jLabel3.setText("ID del Autor:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 17, -1, -1));

        txtIdAutor.setBackground(new java.awt.Color(242, 224, 189));
        txtIdAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtIdAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 14, 143, -1));

        txtNombreAutor.setBackground(new java.awt.Color(242, 224, 189));
        txtNombreAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtNombreAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 38, 268, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 99, 460, 70));

        lstAutores.setBackground(new java.awt.Color(242, 224, 189));
        lstAutores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAutoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstAutores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 220, 291, 149));

        txtBuscar.setBackground(new java.awt.Color(242, 224, 189));
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 190, 291, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 215, 158));
        jLabel4.setText("Buscar (ID o Nombre):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 190, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(17, 92, 58));
        btnAgregar.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 215, 158));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 226, 129, -1));

        btnEliminar.setBackground(new java.awt.Color(166, 66, 34));
        btnEliminar.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 215, 158));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 298, 129, -1));

        btnMostrar.setBackground(new java.awt.Color(242, 224, 189));
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escoba.png"))); // NOI18N
        btnMostrar.setBorderPainted(false);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 334, -1, -1));

        btnEditar.setBackground(new java.awt.Color(27, 73, 125));
        btnEditar.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 215, 158));
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 262, 129, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 620, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 396));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstAutoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAutoresValueChanged
        if (!evt.getValueIsAdjusting()) {
            int index = lstAutores.getSelectedIndex();
            if (index != -1) {
                Autor seleccionado = servicio.listar().get(index);
                txtIdAutor.setText(seleccionado.getId());
                txtNombreAutor.setText(seleccionado.getNombre());
            }
        }
    }//GEN-LAST:event_lstAutoresValueChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        obtenerDatos();
        try{
            servicio.registrar(new Autor(id,nombre));
            limpiar();
        } catch (IllegalArgumentException ex){
            JOptionPane.showMessageDialog(this,
                ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int index = lstAutores.getSelectedIndex();
        if(index !=-1){
            Autor seleccionado = servicio.listar().get(index);
            int opcion = JOptionPane.showConfirmDialog(this,
                "¿Desea eliminar al autor: " + seleccionado.getNombre() + "?",
                "Confirmar eliminación",JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                boolean eliminado = servicio.eliminar(index);
                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Se borro correctamente al autor: " + seleccionado);
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this,"No se puede eliminar: el autor tiene libros asociados.");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int index = lstAutores.getSelectedIndex();
        try{
            if(index!=-1){
                Autor seleccionado = servicio.listar().get(index);
                int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Desea editar al autor: " + seleccionado.getNombre() + "? \n "
                    + "Recuerda que esto se repercutira en todos sus libros asociados",
                    "Confirmar edición",JOptionPane.YES_NO_OPTION);
                if (opcion == JOptionPane.YES_OPTION) {
                    obtenerDatos();
                    servicio.actualizar(index,new Autor(id,nombre));
                    limpiar();
                }
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,
                ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstAutores;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdAutor;
    private javax.swing.JTextField txtNombreAutor;
    // End of variables declaration//GEN-END:variables
}
